name: Tests

on:
  workflow_call: null

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['8.1', '8.2']
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/actions/ci-setup'
        with:
          php-version: ${{ matrix.php-version }}
          php-extensions: openswoole-4.12.0, rdkafka
          extensions-cache-key: tests-extensions-${{ matrix.php-version }}-unit
      - run: composer test:unit:ci
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.php-version == '8.1' }}
        with:
          name: coverage-unit
          path: |
            build/coverage-unit
            build/coverage-unit.cov
